sonar.projectKey=PFT-WEB-SONARQUBE
sonar.host.url=http://localhost:9000
sonar.login=sqp_fc65f0e7d3e3e1ca7f30b2a449aad0dec3fb08ae
sonar.qualitygate.wait=true
sonar.sources=src
sonar.inclusions=**/*.ts,**/*.tsx,**/*.js,**/*.jsx
sonar.exclusions=node_modules/**,public/**,out/**

# Extensiones de archivos reconocidas
# Especificar el lenguaje
sonar.language=TypeScript

# Ruta al archivo tsconfig.json
sonar.typescript.tsconfigPath=tsconfig.json

# Informes de cobertura
sonar.javascript.lcov.reportPaths=coverage/lcov.info
