/**
 * Enumeración para representar los permisos con sus respectivos ID.
 */
enum PermisoEnum {
    ALTA_EQUIPO = 1,
    BAJA_EQUIPO = 2,
    MODIFICACION_EQUIPO = 3,
    OBTENER_EQUIPOS = 4,
    SUBIR_IMAGEN = 5,
    ELIMINAR_IMAGEN = 6,
    MODIFICAR_USUARIO = 7,
    BAJA_USUARIO = 8,
    REACTIVAR_USUARIO = 9,
    MODIFICAR_USUARIO_PROPIO = 10,
    CAMBIAR_ESTADO_USUARIO = 11,
    OBTENER_USUARIOS = 12,
    ALTA_INTERVENCION = 13,
    TRABAJAR_INTERVENCION = 14,
    OBTENER_INTERVENCIONES = 16,
    ALTA_TIPO_INTERVENCION = 17,
    MODIFICAR_TIPO_INTERVENCION = 18,
    BAJA_TIPO_INTERVENCION = 19,
    REACTIVAR_TIPO_INTERVENCION = 20,
    OBTENER_TIPO_INTERVENCIONES = 21,
    REGISTRAR_MOVIMIENTO = 22,
    OBTENER_MOVIMIENTOS = 23,
    ALTA_PERFIL = 24,
    MODIFICAR_PERFIL = 25,
    BAJA_PERFIL = 26,
    REACTIVAR_PERFIL = 27,
    ALTA_UBICACION = 28,
    BAJA_UBICACION = 29,
    OBTENER_UBICACIONES = 30,
    MODIFICAR_UBICACIONES = 31,
}

export default PermisoEnum;
